import{A as v,S as w,K as f,M as y,N as m}from"./assets/vendor-419ba0c6.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const h=document.querySelector(".accordeon-list");new v(h,{duration:600,showMultiple:!0,openOnInit:[0]});const b=document.querySelectorAll(".accordeon-title");b.forEach(r=>{r.addEventListener("click",function(){const s=r.querySelector(".title-icon"),n=r.nextElementSibling;s.classList.toggle("active-is"),n.classList.toggle("hidden")})});const g=document.querySelector(".swiper-next"),L=document.querySelector(".about-me-swiper-container"),d=new w(".about-me-skills",{modules:[f,y],speed:800,loop:!0,slidesPerView:2,slideActiveClass:"swiper-content-wrap-active",keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!0},breakpoints:{375:{slidesPerView:2},768:{slidesPerView:3},1440:{slidesPerView:6}},slideToClickedSlide:!0});g.addEventListener("click",()=>{d.slideNext()});L.addEventListener("keydown",function(r){r.preventDefault(),r.key==="Tab"?d.slideNext():d.slidePrev()});document.addEventListener("DOMContentLoaded",function(){const r=document.querySelector(".reviews-swiper-container"),s=document.querySelector(".reviews-swiper-button-prev"),n=document.querySelector(".reviews-swiper-button-next"),i=new w(r,{modules:[m],slidesPerView:4,spaceBetween:16,navigation:{nextEl:n,prevEl:s},keyboard:!0,breakpoints:{320:{slidesPerView:1},340:{slidesPerView:1},768:{slidesPerView:2},1024:{slidesPerView:4}}});e();async function e(){try{const o=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!o.ok)throw new Error("Failed to fetch reviews");const a=await o.json();if(a.length===0){c();return}t(a)}catch(o){console.error("Error fetching reviews:",o),p("Failed to fetch reviews. Please try again later.")}}function t(o){const a=o.map(l=>`
        <div class="swiper-slide">
          <div class="review-card">
            <img src="${l.avatar_url}" alt="${l.author}'s avatar" class="review-avatar" />
            <div class="review-author">${l.author}</div>
            <div class="review-text">${l.review}</div>
          </div>
        </div>
      `).join("");r.querySelector(".reviews-swiper-wrapper").innerHTML=a,i.update(),u()}function c(){r.querySelector(".reviews-swiper-wrapper").innerHTML='<p class="not-found">No content available</p>',i.destroy()}function p(o){alert(o)}function u(){i.isBeginning?s.classList.add("swiper-button-disabled"):s.classList.remove("swiper-button-disabled"),i.isEnd?n.classList.add("swiper-button-disabled"):n.classList.remove("swiper-button-disabled")}i.on("slideChange",u)});
//# sourceMappingURL=commonHelpers.js.map
