import{S as p}from"./assets/vendor-f5ebb2c2.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",function(){const a=document.querySelector(".swiper-container"),i=document.querySelector(".swiper-button-prev"),o=document.querySelector(".swiper-button-next"),r=new p(a,{slidesPerView:4,spaceBetween:20,navigation:{nextEl:o,prevEl:i},keyboard:!0,breakpoints:{320:{slidesPerView:1},340:{slidesPerView:2},768:{slidesPerView:3},1024:{slidesPerView:4}}});e();async function e(){try{const s=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!s.ok)throw new Error("Failed to fetch reviews");const c=await s.json();if(c.length===0){n();return}t(c)}catch(s){console.error("Error fetching reviews:",s),u("Failed to fetch reviews. Please try again later.")}}function t(s){const c=s.map(d=>`
        <div class="swiper-slide">
          <div class="review-card">
            <img src="${d.avatar_url}" alt="${d.author}'s avatar" class="review-avatar" />
            <div class="review-author">${d.author}</div>
            <div class="review-text">${d.review}</div>
          </div>
        </div>
      `).join("");a.querySelector(".swiper-wrapper").innerHTML=c,r.update(),l()}function n(){a.querySelector(".swiper-wrapper").innerHTML='<p class="not-found">No content available</p>',r.destroy()}function u(s){alert(s)}function l(){r.isBeginning?i.classList.add("swiper-button-disabled"):i.classList.remove("swiper-button-disabled"),r.isEnd?o.classList.add("swiper-button-disabled"):o.classList.remove("swiper-button-disabled")}r.on("slideChange",l)});
//# sourceMappingURL=commonHelpers.js.map
